### ISSUE TITLE
Scroll bar ajustments

### ISSUE THREAD

**Issue by craigdrown** [sussol/universal-drug-codes-web-app#38]
1. Should scroll on list only, not on outer container that includes header
2. Header rows shouldn't scroll
3. @andreievg suggested to disable scroll (overflow: disabled ?) on body, set body height to 100% so scrolling is just on the list

**Comment by jtrein** [comment]
Yeah, I'll fix :-) I was aware of these when I pushed, but they were initially bearable for example.
